# Generated by Django 5.0.9 on 2024-10-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0005_alter_curso_codigo_alter_matricula_estudante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudante',
            name='data_nascimento',
            field=models.DateTimeField(blank=True),
        ),
    ]
